<?php

namespace AppBundle\Repository;

/**
 * CocheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CocheRepository extends \Doctrine\ORM\EntityRepository
{
}
